api:
  image: imagegwapi
  ports:
   - 5555:5000
  links:
   - mongo
   - systema
   - registry
  volumes:
   - imagegw:/data
   - ./test/config:/config
  command: munge:systema:munge munge:systemb:munge api
mongo:
  image: mongo:2.6
  volumes:
    - /data/db
  command: --smallfiles
systema:
  container_name: systema
  image: shifter-test
  extra_hosts:
   - "api:172.17.0.1"
   - "registry:172.17.0.1"
  ports:
   - "2222:22"
  volumes:
  - /images
  - ./test/config/:/config
  privileged: true
  environment:
  - ADDUSER=canon
registry:
  image: registry
  ports:
   - "5000:5000"
  volumes:
  - registry:/var/lib/registry
