
REDIS_PASSWORD=mypassword

all:

test/config/redis.conf: Makefile.test
	echo "requirepass $(REDIS_PASSWORD)" > test/config/redis.conf
	echo 'rename-command CONFIG ""' >> test/config/redis.conf
	sed -i -e 's/redis:\/\/:.*@/redis:\/\/:$(REDIS_PASSWORD)@/' ./test/config/imagemanager.json

test/config/ssh.key:
	ssh-keygen -t rsa -f test/config/ssh -N '' -C 'Test key'
	mv test/config/ssh test/config/ssh.key


test/config/munge.key:
	dd if=/dev/urandom bs=1 count=1024 > test/config/munge.key 

testprep: test/config/redis.conf test/config/ssh.key test/config/munge.key
	docker volume inspect imagegw || docker volume create --name imagegw

startdeps:
	docker run -d --name mongot -p 27017:27017 mongo --smallfiles
	docker run -d --name redist -p 6379:6379 redis

starttest: testprep
	docker build -t imagegwapi .
	docker build -t shifter-test ..
	docker-compose up -d

restartgw:
	docker build -t imagegwapi .
	docker-compose up -d

getssh:
	$(eval IP=$(shell docker-machine ip $(shell docker-machine active)))
	$(eval PORT=$(shell docker-compose ps systema|grep systema|sed 's/.*://'|sed 's/-.*//'))
	@echo "To connect, do:"
	@echo "ssh -i test/config/ssh.key $(IP) -p $(PORT)"

cleanup:
	docker-compose stop
	docker images -f dangling=true -q|xargs docker rmi
