#! /bin/bash
#
#
# Author:
#    Miguel Gila <miguel.gila@cscs.ch>
#
#

if [ -z ${ROOT_TREE} ]; then
  ROOT_TREE='/opt/shifter/15.12.0'
fi

if [ -z ${PYTHON_VENV} ]; then
  PYTHON_VENV='imagegw_venv'
fi

sudo yum install -y mongodb-server mongodb redis
sudo /etc/init.d/mongod start
sudo /etc/init.d/redis start

cd ${ROOT_TREE}
MYPYTHONPATH=${ROOT_TREE}/python_2.7.9
wget 'https://www.python.org/ftp/python/2.7.9/Python-2.7.9.tgz'
cd Python-2.7.9/
./configure --prefix=$MYPYTHONPATH
make -j4 && make install
cd ..
find ./Python-2.7.9 -exec rm -rf {} \;

wget 'https://pypi.python.org/packages/source/v/virtualenv/virtualenv-13.1.2.tar.gz#md5=b989598f068d64b32dead530eb25589a'
tar xzvf virtualenv-13.1.2.tar.gz
virtualenv-13.1.2/virtualenv.py imagegw_venv --python=$MYPYTHONPATH/bin/python2.7

source imagegw_venv/bin/activate
pip install celery pymongo flask pysocks redis flower requests
