#!/usr/bin/env python
import sys
from os import symlink
from os.path import exists
from docker import Client
c = Client(base_url='unix://var/run/docker.sock')

linkbase="/tmp/"
dbase="/var/lib/docker/graph/"


def lookup(name):
  lst = c.images()
  image=0
  for i in lst:
    for tag in i['RepoTags']:
     if tag==name:
       image=i
  return image


name=sys.stdin.readline().rstrip()

image=lookup(name)

if image==0:
  c.pull(name)
  image=lookup(name)

print dbase+image['Id']
if image != 0:
  if exists(linkbase+name)==False:
    symlink(dbase+image['Id'],linkbase+name)
  print 1
else:
  print 0
