#!/bin/sh
#
# Mock tar
# This is just to hide errors that seem to only happen in a docker container.
# So, let's just ignore tar errors for now.
#

if [ -e /bin/tar ] ; then
  TAR=/bin/tar
elif [ -e /usr/bin/tar ] ; then
  TAR=/usr/bin/tar
else
  echo "tar not found" 1>&2
  exit 1
fi

$TAR $(echo "$@"|sed 's/--force-local//')
exit 0
