#!/bin/sh
#
# Mock unmunge command - For testing purposes only
#
T=$(dirname $0)

IN=$(cat)
MT=$(cat $T/munge.test)
EX=$(cat $T/munge.expired)
REP=$(cat $T/munge.replay)

if [ "$IN" == "$MT" ] ;then
  ST="Success (0)"
  RT=0
  # Mimic unmunging the same thing twice
  cat $T/munge.test > $T/munge.replay
  echo "" > $T/munge.test
elif [ "$IN" == "$EX" ] ;then
  ST="Expired credential (15))"
  RT=15
elif [ "$IN" == "$REP" ] ;then
  ST="Replayed credential (17)"
  RT=17
else
  echo "unmunge: Error: Failed to match armor prefix"
  exit 8
fi

DS=$(TZ=GMT date +"%Y-%m-%d %H:%M:%S %z (%s)")

cat << EOF
STATUS:           $ST
ENCODE_HOST:      4175821389c5 (172.17.1.59)
ENCODE_TIME:      2015-10-15 14:56:43 +0000 (1444921003)
DECODE_TIME:      $DS
TTL:              300
CIPHER:           aes128 (4)
MAC:              sha1 (3)
ZIP:              none (0)
UID:              root (0)
GID:              root (0)
LENGTH:           0

test
EOF

exit $RT
