#!/bin/bash

APRUN=`which aprun`
SRUN=`which srun`

declare -a args=("$@")
job=0
[[ -n "$PBS_JOBID" ]] && job="$PBS_JOBID"
[[ -n "$SLURM_JOBID" ]] && job="$SLURM_JOBID"
datadir="/var/run/udiRoot_run/$USER/$job"

[[ "$job" == "0" ]] && die "Couldn't identify job"

## allowed environment variables
whiteListPrefix="SLURM PBS BASH_FUNC ALPS"
whiteList="NERSC_HOST CRAY_ROOTFS"

## strip environment
while IFS= read -r -d '' item; do
    IFS="="
    set -- $item
    unset IFS
    varName="$1"
    for prefix in $whiteListPrefix; do
        [[ -z "$prefix" ]] && continue
        [[ "$varName" = "$prefix"* ]] && continue 2
    done
    for var in $whiteList; do
        [[ -z "$var" ]] && continue
        [[ "$varName" = "$var" ]] && continue 2
    done

    unset "$varName"
done < <(env -0)

## source special image environment
newVars=""
if [[ -e "$datadir/env" ]]; then
    while IFS= read -r -d '' item; do
        IFS="="
        set -- $item
        unset IFS
        newVars="$1 $newVars"
    done < <(cat "$datadir/env")
    source "$datadir/env"
    for var in $newVars; do
        export "$var"
    done
fi

## ensure that udiRoot ssh is superior in path
export PATH="/opt/udiImage/bin:$PATH:/usr/bin:/bin"

aprunCmd=("$APRUN" "-b")
while IFS= read -r  -d '' item; do
    IFS="="
    set -- $item
    unset IFS
    varName="$1"
    [[ "$varName" = "BASH_FUNC"* ]] && continue
    value=$( echo $item | awk -F= '{ $1=""; print $0; }' | sed 's/^ //g' )
    aprunCmd=("${aprunCmd[@]}" "-e" "$varName=\"$value\"")
done < <(env -0)

aprunCmd=("${aprunCmd[@]}" "${args[@]}")
exec "${aprunCmd[@]}"
