name: Integration Tests

on:
  push:
    branches:
    - main
    - sanic
    - gha
  pull_request:
    branches: 
    - main
    - sanic

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Install dependencies
        run: |
           sudo chmod 755 /var/log
           sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ bionic universe multiverse"
           sudo apt-get update -qq
           sudo apt-get install -qq libjson-c-dev munge libmunge2 libmunge-dev libcurl4-openssl-dev autoconf automake libtool curl make valgrind xfsprogs squashfs-tools libcap-dev
           sudo modprobe squashfs
           sudo modprobe xfs
           pip install -r imagegw/requirements.txt
           pip install coverage
           pip install cpp-coveralls
           pip install coveralls
           pip install coveralls-merge
           pip install pexpect
#  - LOC=$(dirname $(which coveralls) ); sudo mv $LOC/coveralls $LOC/cpp-coveralls

      - name: Integration Tests
        run: |
          cp imagegw/test.json.example test.json
          mkdir /tmp/imagegw /tmp/systema /tmp/systemb
          rm imagegw/test/sha256sum
          echo "Disabling autoclear for Travis and Kernel 5.4"
          sed -i 's/useAutoclear = 1;/useAutoclear = 0;/' ./src/shifter_core.c
          export PROC_COUNT=$(cat /proc/cpuinfo  | egrep '^processor' | wc -l)
          ./autogen.sh
          ./configure --prefix=/usr --sysconfdir=/etc/shifter --disable-staticsshd
          MAKEFLAGS="-j$PROC_COUNT" make
          MAKEFLAGS="-j$PROC_COUNT" make check
          sudo make install 
          cd src/test
          export DO_ROOT_TESTS=1
          export DO_ROOT_DANGEROUS_TESTS=1
          ../../extra/CI/test_script.sh
          cd ../..
          export ORIGPATH=$PATH
          export PATH=$PWD/imagegw/test:$PATH
          PYTHONPATH=$PWD/imagegw nosetests -s --with-coverage imagegw/test
          export PATH=$ORIGPATH
          export BUILDDIR=$(pwd)
          cd /
          $BUILDDIR/extra/CI/integration_test.sh
          cd $BUILDDIR

#after_success:
##  - cpp-coveralls --exclude dep -n --dump cpp_coveralls.json
#  - coveralls-merge cpp_coveralls.json 
#notifications:
