name: "Pull Request Docs Check"
on:
  - pull_request

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
